### ISSUE TITLE
No separate context-sub-menu 

### ISSUE THREAD

**Issue by janwilmans** [djeedjay/DebugViewPP#106]
Process->Contextmenu->Exclude was very nice, I vote to remove the sub-menu, and just have all options in the main-context-menu

**Comment by janwilmans** [comment]
Also add keyboard-shortcuts (accelerator keys?) for the filter options.

**Comment by janwilmans** [comment]
keyboard-shortcuts do not make sense for filters, as a filter must always be based on a selection (currently either text from a message or a processname)

**Comment by djeedjay** [comment]
Is dat zo? Ik kan me voorstellen dat je bijv. met ^E de geselecteerde text als exclude filter toevoegt.

Gert-Jan

**Comment by janwilmans** [comment]
Hm, ok, ik zal het eens proberen :) de shortcut keys leken me wel handig
namelijk.

Ik ontdek net een bug:

Als je "DbgMsgSrc.exe -7" gebruikt en in de regel:

515 35.346069 7612 DbgMsgSrc.exe A B C D E

A t/m E probeert te highlighten, dan werkt dat niet meer :( dat zijn weer
die regels met tabs erin)
C t/m E proberen te highlighten, geeft zelft een foutmelding.

Kun jij eens kijken? Ik denk dat ik die tabs-oplossing niet goed gemaakt
heb.

Groeten,

Jan

Ps. copyeren met CTRL-C naar clipboard werkt goed in the head-versie
volgens mij, dus dat zal misschien een bug uit voor oudere versie zijn.






On 12 September 2015 at 11:03, Gert-Jan de Vos <notifications@github.com>
wrote:

> Is dat zo? Ik kan me voorstellen dat je bijv. met ^E de geselecteerde text
> als exclude filter toevoegt.
>
> Gert-Jan
>
> > On 12 Sep 2015, at 10:59, Jan Wilmans <notifications@github.com> wrote:
> >
> > keyboard-shortcuts do not make sense for filters, as a filter must
> always be based on a selection (currently either text from a message or a
> processname)
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/djeedjay/DebugViewPP/issues/106#issuecomment-139741680
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djeedjay/DebugViewPP/issues/106#issuecomment-139741819>
> .
>



-- 
Met vriendelijke groeten,

Jan Wilmans

**Comment by janwilmans** [comment]
close by accident, reopen to investigate gert-jan's suggestion

**Comment by janwilmans** [comment]
I problem that might be overlooked here is that searching for regex "C\tE"
should probably highlight the text "C\s\s\sE" when found...

Greetings,

Jan

2015-09-12 11:31 GMT+02:00 Jan Wilmans <janwilmans@gmail.com>:

> Hm, ok, ik zal het eens proberen :) de shortcut keys leken me wel handig
> namelijk.
>
> Ik ontdek net een bug:
>
> Als je "DbgMsgSrc.exe -7" gebruikt en in de regel:
>
> 515 35.346069 7612 DbgMsgSrc.exe A B C D E
>
> A t/m E probeert te highlighten, dan werkt dat niet meer :( dat zijn weer
> die regels met tabs erin)
> C t/m E proberen te highlighten, geeft zelft een foutmelding.
>
> Kun jij eens kijken? Ik denk dat ik die tabs-oplossing niet goed gemaakt
> heb.
>
> Groeten,
>
> Jan
>
> Ps. copyeren met CTRL-C naar clipboard werkt goed in the head-versie
> volgens mij, dus dat zal misschien een bug uit voor oudere versie zijn.
>
>
>
>
>
>
> On 12 September 2015 at 11:03, Gert-Jan de Vos <notifications@github.com>
> wrote:
>
>> Is dat zo? Ik kan me voorstellen dat je bijv. met ^E de geselecteerde
>> text als exclude filter toevoegt.
>>
>> Gert-Jan
>>
>> > On 12 Sep 2015, at 10:59, Jan Wilmans <notifications@github.com> wrote:
>> >
>> > keyboard-shortcuts do not make sense for filters, as a filter must
>> always be based on a selection (currently either text from a message or a
>> processname)
>> >
>> > —
>> > Reply to this email directly or view it on GitHub <
>> https://github.com/djeedjay/DebugViewPP/issues/106#issuecomment-139741680
>> >.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/djeedjay/DebugViewPP/issues/106#issuecomment-139741819>
>> .
>>
>
>
>
> --
> Met vriendelijke groeten,
>
> Jan Wilmans
>



-- 
Met vriendelijke groeten,

Jan Wilmans

**Comment by janwilmans** [comment]
Tested: shortcut keys work fine on selections. In fact, this works GREAT, implementing...
