### ISSUE TITLE
Delay application feature

### ISSUE THREAD

**Issue by janwilmans** [djeedjay/DebugViewPP#125]
Add a feature to make to make the DBWinBuffer receiver slow, this can help to debug timing issues.

**Comment by djeedjay** [comment]
Propose to reject. Tools like CPU burner or drMemory are better tools for this. DebugView is a log viewer, not a debugger or run time code analysis tool.

**Comment by janwilmans** [comment]
Agreed, the only reason why it is in here, it because it contributes to
'full dbgview replacement', some users reported that they were using
dbgview in order to introduce the delay.

On 27 September 2015 at 14:22, Gert-Jan de Vos <notifications@github.com>
wrote:

> Propose to reject. Tools like CPU burner or drMemory are better tools for
> this. DebugView is a log viewer, not a debugger or run time code analysis
> tool.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djeedjay/DebugViewPP/issues/125#issuecomment-143546438>
> .
>



-- 
Met vriendelijke groeten,

Jan Wilmans

**Comment by djeedjay** [comment]
Good. People who prefer dbgview will know where to find it :-)
I
Gert-Jan

**Comment by janwilmans** [comment]
Marked as wontfix, debugview++ is not a debugger.
