### ISSUE TITLE
The status bar flickers continuously

### ISSUE THREAD

**Issue by janwilmans** [djeedjay/DebugViewPP#132]
it is now updated also when it is not dirty, but that is not the problem, although it might make the effect worse, the status bar is now drawn with only an empty background for some frames (at least that is what it looks like), observed in windows7

**Comment by janwilmans** [comment]
Tried to apply gert-jan's COffscreenPaint solution to the status bar but the result is the status bar's regions do not get drawn anymore. (no flicker either though :)

class CMultiPaneStatusBarCtrlFlickerFree :					// CMultiPaneStatusBarCtrl replacement
	public CMultiPaneStatusBarCtrlImpl<CMultiPaneStatusBarCtrlFlickerFree>,
	public COffscreenPaint<CMultiPaneStatusBarCtrlFlickerFree>
{
public:
	DECLARE_WND_SUPERCLASS(nullptr, CMultiPaneStatusBarCtrlImpl<CMultiPaneStatusBarCtrlFlickerFree>::GetWndClassName())  

	BEGIN_MSG_MAP(CMultiPaneStatusBarCtrlFlickerFree)
		CHAIN_MSG_MAP(COffscreenPaint<CMultiPaneStatusBarCtrlFlickerFree>)
	END_MSG_MAP()

	void DoPaint(CDCHandle dc, const RECT& rcClip) override
	{
		dc.FillSolidRect(&rcClip, Colors::BackGround);
		DefWindowProc(WM_PAINT, reinterpret_cast<WPARAM>(dc.m_hDC), 0);
	}

};

**Comment by djeedjay** [comment]
Ha,

Jouw aanpak is okee maar om onduidelijke redenen werkt dit niet voor een status bar…

Gert-Jan
