### ISSUE TITLE
Find Text Entry Control drops the letters EHIKehik

### ISSUE THREAD

**Issue by MarkGoldberg** [djeedjay/DebugViewPP#189]
To reproduce the issue:
- give focus to the entry to the right of Find:
- type the whole alphabet, upper and lower case
- observe bug: the letters EHIKehik are not present

NOTE: there is nothing special about the whole alphabet or the order the letters are entered.
NOTE: Tests showed that all other symbols on my keyboard worked correctly.

Workaround: use the clipboard and paste the desired string into the find entry control

First Noticed in Version 1.4.0.3

**Comment by janwilmans** [comment]
Thanks for reporting!! I just added shortcut keys for 
Ctrl-E
Ctrl-H
Ctrl-I
and Ctrl-K, so probably explains it.

**Comment by MarkGoldberg** [comment]
Additional detail: Apparently SHIFT HIKE all work
But CapLocks HIKE fails

**Comment by MarkGoldberg** [comment]
oh crap, I didn't mean to close the issue. (blush)

**Comment by djeedjay** [comment]
Ha,

Ik dacht te hebben gezien dat je shortcuts hebt gemaakt zonder modifiers.
Dan kun je dus niet meer normaal typen..

De shortcuts zouden inderdaad met Ctrl moeten zijn.


> Thanks for reporting!! I just added shortcut keys for
> Ctrl-E
> Ctrl-H
> Ctrl-I
> and Ctrl-K, so probably explains it.

Gert-Jan

**Comment by janwilmans** [comment]
@djeedjay : kunnen de 'delete' ook alleen laten werken als de focus op een line staat? ik heb er voor nu maar ctrl-delete van gemaakt

**Comment by janwilmans** [comment]
Mark: I've fixed the issue, a new binary will be available soon

**Comment by djeedjay** [comment]
Hmm.. Het idee van hotkeys is nu juist dat ze altijd werken. Toch moet het
kunnen, er zijn browsers met hotkeys die je ook in entry fields kunt
intiepen.
Vanavond maar weer eens wat googlen.

G-J

**Comment by janwilmans** [comment]
@MarkGoldberg : the download links have been updated with the latest head-version fixing this issue
