### ISSUE TITLE
Regular expression error window does not say 'which' expression has an error

### ISSUE THREAD

**Issue by janwilmans** [djeedjay/DebugViewPP#195]
Although you mostly remember what you're editing, to could be nice to set the focus on the cell with the error.

![image](https://cloud.githubusercontent.com/assets/5933444/10122870/f8fea350-6527-11e5-8158-45fdaa879d1c.png)

**Comment by djeedjay** [comment]
Fixed in commit 3eb7607bf5cbf17f3d1fb16d39ab08b5b28b779e
