### ISSUE TITLE
ESC key does not work if filter-line has focus

### ISSUE THREAD

**Issue by janwilmans** [djeedjay/DebugViewPP#205]
ESC works if only if any other control on the filter-dialog has focus, it closes the window like 'cancel', but if a grid-item has focus, it looks like to ESC key is send to the grid, and not passed to the window

**Comment by janwilmans** [comment]
Now that the grid has focus by default, ESC appears not the work at all, in fact it does work, but just not when the grid has focus. I wonder why ESC works normally when the 'view name' field in focussed

**Comment by djeedjay** [comment]
Esc means “End cell edit” when the grid has focus.

**Comment by janwilmans** [comment]
closing as 'normal' behaviour
