### ISSUE TITLE
strange filter behaviour on processes tab

### ISSUE THREAD

**Issue by janwilmans** [djeedjay/DebugViewPP#207]
- the last item in not focussed initially
- when 'RegexGroups' is selected, the type 'Stop' is automatically selected?
- the auto-color is also available here? I could not figure out any useful behaviour for it.

Maybe we should remove the View-> 'Process Colors' menu item and have 'highlight' and 'include' have that effect if auto-color is enabled.

For example:

Filter: "dbg", match "simple", type: "include" + auto color

would auto-color only processes that match the word 'dbg'.

**Comment by djeedjay** [comment]
We could implement ‘Process Colors' like that but it would be rather cryptic to present it to the user like that. Process Colors now basically does:
 “.*”, Regex, Highlight, Auto Bg. Adding Auto Bg to ProcessFilters allows color matching for partial process name matches. Is there any use for that?

Bullets 2 and 3 are fixed.

**Comment by janwilmans** [comment]
Well I can imagine, suppose someone would have multiple processes, lets say some completely random name like 'feibbox.exe' it might be usefull to highlight only highlight those processes...

**Comment by janwilmans** [comment]
But I do agree that it is very cryptic and you probably want “.*”, Regex, Highlight, Auto Bg 99% of the time. You can also filter other processes and make view for just your processes of interest.

**Comment by janwilmans** [comment]
ok, everything is back to normal, and the idea to include 'auto-clolor' on the process tab does not seem like a very good one, I'm closing this issue
