### ISSUE TITLE
After installation, cannot find program in start menu (Windows 10)

### ISSUE THREAD

**Issue by justanotheranonymoususer** [djeedjay/DebugViewPP#211]
Seems like DVPP creates a non-standard shortcut. Removing it and creating a new shortcut manually fixes the issue.

**Comment by janwilmans** [comment]
thanks for reporting, I think this must be a windows 10 thing, we do not create the shortcut at all, this is automated in the installer, so we should probably have so windows 10 installer support :) we will check it out!

**Comment by janwilmans** [comment]
Fixed by using a newer wix version
