### ISSUE TITLE
dragging a selection off-screen causes access violations

### ISSUE THREAD

**Issue by janwilmans** [djeedjay/DebugViewPP#214]
Now also seen in release-mode, so nolonger a debug-mode artifact, so created issue.

**Comment by djeedjay** [comment]
Can you describe a specific example which reproduces this crash?

**Comment by janwilmans** [comment]
Well, I just started debugview++ and selected a word, and bam...but now...
so I thought it was easy, but now I cant reproduce it.

On 19 November 2015 at 16:16, Gert-Jan de Vos <notifications@github.com>
wrote:

> Can you describe a specific example which reproduces this crash?
>
> > Now also seen in release-mode, so nolonger a debug-mode artifact, so
> > created issue.
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/djeedjay/DebugViewPP/issues/214
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djeedjay/DebugViewPP/issues/214#issuecomment-158086388>
> .
>



-- 
Met vriendelijke groeten,

Jan Wilmans

**Comment by djeedjay** [comment]
I now also see occasional problems. Both non-stop scrolling and disappearing messages. No explanation yet.

Gert-Jan

**Comment by janwilmans** [comment]
not seen anymore, closing...
