### ISSUE TITLE
Can't save Log file in negative time zones

### ISSUE THREAD

**Issue by BillSTP** [djeedjay/DebugViewPP#226]
Attempting to save log file gives a "FileTimeToSystemTime: The parameter is incorrect" error message.
A "dblog" file is created but it's empty. Getting this on several systems (PC, tablet). Noticed this behavior after latest Windows 10 update. Running version 1.4. Tried using version 1.6 but same error situation.

**Comment by janwilmans** [comment]
Thanks for reporting, I have had more windows 10 issues reported, I hoped they would go away with new windows 10 updates but it seems like that is not going to happen :) I'll install windows 10 in a virtual machine and see what I can do.

**Comment by BillSTP** [comment]
I'm testing some software on a Win 10 tablet and then sending the debug log
file over to my Win 10 PC.

My workaround for now is to run version 1.2 on the tablet (which does let
me save the log correctly)
and then view it on the PC (using version 1.4).

**Comment by janwilmans** [comment]
Ok, I've tested on Windows 10 Professional, and it does not reproduce for me, I'm guessing it has something to do with a change I made in the way timestamps are saved. Can you give me more details? Does the error occur on the PC side as well, or only one the tablet.
what are the regional settings of the tablet?

Also, are you aware that you run dbgview-agent on it the tablet (it is available from microsoft) and debugview++ can connect to it, just like dbgview. That way, you can have 'runtime / live' view the messages instead of load/saving.

**Comment by BillSTP** [comment]
*I've tested on Windows 10 Professional...*

I'm running Windows Home on the PC and the tablet (both have latest Win 10
update).

* Does the error occur on the PC side as well, or only one the tablet...*

Same problem on PC and tablet. Same error message. And on both, an empty
log file is created.

*what are the regional settings of the tablet...*


​

*Also, are you aware that you run dbgview-agent on it the tablet...*

Yup but I've never been able to get them to connect.
DebugView puts up its "Waiting To Connect" messagebox on the tablet
and when I try use the "Connect Debug View Agent" option on DebugView++,
on the remote PC, it logs a "connection refused by target machine" error
message.
Tried tweaking the firewall on the tablet to no avail.

Seems like a nice feature. But, in for the sake of expediency, I ended doing
the "save log on the remote from the tablet" procedure. not as elegant
but it gets the job done.

By the way, nice job on DebugView++. The colorized processes and the
filtering options are a pleasure to use.

Bill :-)

**Comment by janwilmans** [comment]
Bill, would you be willing to help solve the problem? I have a test-version I can share to debug the problem, please email me directly ( janwilmans at gmail dot com)

**Comment by janwilmans** [comment]
Thanks for the info bill, I have found the issue and will create a patch shortly

**Comment by janwilmans** [comment]
Actually, it turns out this is not windows 10 related at all. Any save attempt in a negative timezone (UTC-N) will fail because the header line is trying to save the FILETIME "0" which translates into a systemtime before 1601/01/01, which is not acceptable.
