### ISSUE TITLE
File->Open 'keep file open' has side-effects

### ISSUE THREAD

**Issue by janwilmans** [djeedjay/DebugViewPP#228]
CMainFrame::OnFileOpen Load / LoadAsync have completely different behaviour
Other then 'keep file open' it should behave the same; _which means_ loading very large files should not block the ui, but just read using LoadAsync but not keep tailing it.

**Comment by harriv** [comment]
Trying to open larger log file  (about 60000 rows) loads only small part of lines if "Keep file open" is not checked. Maybe related to this?

**Comment by janwilmans** [comment]
I think I found the problem, thanks for reporting again!
