### ISSUE TITLE
View/Filter Settings dialog Background & Foreground color selection in one dialog

### ISSUE THREAD

**Issue by RichardKNS** [djeedjay/DebugViewPP#239]
In the View/Filter settings dialog, for changing back- and foreground colors it requires closing the color selection dialog for the background color and opening the color selection dialog again for the foreground color.
It is possible to create one color selection dialog that allows you to select the back- AND foreground color in one dialog ?

This would be a nice enhancement.

**Comment by janwilmans** [comment]
I really appreciate you taking the time to suggest improvements!
I will look into this, but I have a feeling this it rather more difficult that you would expect. We use WTL to call standard windows color-selection dialogs and I suspect that just don't have to ability to do what you describe.

**Comment by janwilmans** [comment]
I've looked at this, its really more trouble then I'd like to invest on this. It would have to be a custom color-picker from scratch, it is quite a bit of work, I'm closing this issue.
