### ISSUE TITLE
DebugviewPP with IIS

### ISSUE THREAD

**Issue by Afrit123** [djeedjay/DebugViewPP#242]
DebugviewPP doesn't seem to work properly with IIS. The normal debugview application does work. Both have the option capture global win32 on. When using DebugviewPP it doesn't capture my application tracing. Debugview does.

**Comment by janwilmans** [comment]
This might depend on the user-account the IIS is running in, and also might be related to whether you start debugview++ as 'run as administrator'. 

Debugview uses API-hooking to capture its messages, so it is able to capture message even when a debugger is attached (such as visual studio). DebugView++ cannot do this. However, I have written a plugin for visual studio that forwards debug-messages from visual studio to debugview++, let me know if you would like to try it.

**Comment by Afrit123** [comment]
Hi, Thanks for your suggestion. I do run it as administrator. I use a web application in Lua which doesn't use an IDE like visual studio. I was using abyss webserver before and then debugviewpp did work. After i switched to IIS it didn't work anymore. I really hope this can be fixed because the normal debugview is a pain.

**Comment by janwilmans** [comment]
I will have to understand how ISS is running I think, however, I am not a web-developer and I know nothing about ISS or how to run anything 'in' ISS.

The best I can do for now, I guess, is suggest to run the dbgview-agent, and connect debugview++ to that.
See https://github.com/djeedjay/DebugViewPP/ look for 'Connect to sysinternals dbgview agent for kernel messages' 

It's definitely a workaround, but I think it will work...

**Comment by Afrit123** [comment]
Thanks. I tried it but it also doesn't work. I added the /g switch on top of the /a and /k to also catch global win32 but it still doesn't work. debugview++ does connect to the agent and everything looks good, but the debug messages don't show up.

I guess i'll just have to keep using the normal debugview. Thanks for your time!

**Comment by janwilmans** [comment]
nothing more to do I guess, unfortunately we couldn't solve the issue, closing.

**Comment by rhythmnewt** [comment]
Make sure your application pool in IIS is running under a local admin account (maybe domain admin would work too but haven't checked), not ApplicationPoolIdentity or regular user account. 

Once the app pool is running under admin, you can run DebugViewPP as admin and view the debug and trace messages. 

I don't know enough about internals to say why running DebugViewPP as Admin does not capture the Global Win32 Messages without this specific config but the original DebugView does. I am using the MSI version of the DebugViewPP v1.8.0.34.

This is confirmed working on Windows 10 with IIS 10.

**Comment by janwilmans** [comment]
Thanks for the update!
