### ISSUE TITLE
missing enable/disable all checkbox

### ISSUE THREAD

**Issue by janwilmans** [djeedjay/DebugViewPP#246]
![image](https://cloud.githubusercontent.com/assets/5933444/20561407/c94cd696-b17e-11e6-9e89-3c2e773e7845.png)

**Comment by janwilmans** [comment]
very nice :)

**Comment by djeedjay** [comment]
Ha,

De nieuwe checkbox is niet zichtbaar in WinXP, maar dat lijkt me niet zo’n probleem.

Groeten,

Gert-Jan
