### ISSUE TITLE
Proposal: add escape key to close the filter settings dialog

### ISSUE THREAD

**Issue by janwilmans** [djeedjay/DebugViewPP#247]
many (but not all) windows on windows 7/8/10 can be closed with the Escape-key, examples are:

- Debugview->open file dialog 
- Debugview-> about dialog

but 
- View->Filters does not respond to Escape
- also Log->Sources does not response to Escape

Its very handy, but I could not get it in the filter-dialog as global key...

**Comment by djeedjay** [comment]
Ha,

Ik heb de auteur van het property grid control om advies gevraagd. Het control claimde alle keys om navigatie in het control mogelijk te maken. Ik heb dat weer terug naar default key handling gemaakt en escape/return gedragen zich nu weer naar behoren. Ik vermoed dat er nu iets niet meer goed werkt in het property grid. Kun jij ook eens proberen of het nu goed werkt? Ik denk dat ik nu we weet waar ik evt. aanpassingen in het grid control kan maken.

Groeten,

Gert-Jan

**Comment by janwilmans** [comment]
Bedankt! Ik ga het  testen!

Groeten,

Jan
