### ISSUE TITLE
UDP default port incorrect, and greyed out

### ISSUE THREAD

**Issue by codenotes** [djeedjay/DebugViewPP#259]
When trying to set up a UDP source, it defaults to 192.168.1.1.  That isn't the correct IP, but it is greyed out.  In order to change it to a working ip, I need to switch to "Debug Agent", change the ip, then switch it back to UDP and then click OK.

**Comment by janwilmans** [comment]
fixed by 83eb863315767cd028272951032bb517c01ea6ae
