### ISSUE TITLE
Ctrl-Shift-X doesnt work 100%, yet Logs, Clear Log does

### ISSUE THREAD

**Issue by mriffey** [djeedjay/DebugViewPP#286]
Not long ago we were talking about Ctrl-X vs Ctrl-Shift-X. On the latest 64 bit build (.98), Ctrl-Shift-X appears to perform a ctrl-X (clearing the log display), but I dont see the memory load (lower right corner) change. If I then go to Log, Clear Log on the menu, the memory load immediately drops. Is there a delay in the update of that value, or is this a bug?

**Comment by janwilmans** [comment]
yes, must be a gui-update delay bug, because, that menu-item and its shortcut key refer to the same method. I will look into it, thanks for reporting!

**Comment by mriffey** [comment]
https://www.screencast.com/t/aRV6NLmXnscj  Saw it this am, a bit more obvious since the log was 11 meg before clearing and 2 meg after clicking log, clear log.

**Comment by janwilmans** [comment]
and pressing ctrl shift x multiple times has no effect?

**Comment by janwilmans** [comment]
Ctrl-Shift-x no working on all os's ?

**Comment by mriffey** [comment]
New info...  Works on Win10, doesnt work on Win2012 Server. Specifically, the ctrl-shift-X causes no change in view, log or memory display on Server 2012. When I use the menu "Clear log" function, the log and display are cleared as expected. 

WMIC info follows: 

![debugviewissue](https://user-images.githubusercontent.com/2301643/28801977-77d1adac-7611-11e7-87b0-591c9e68cd69.png)

**Comment by mriffey** [comment]
On a whim, I tried the on screen keyboard (OSK.exe) to press Ctrl-Shift-X and the log cleared. This one is on MSFT:)
