### ISSUE TITLE
Highlight only the groups in regular expressions

### ISSUE THREAD

**Issue by janwilmans** [djeedjay/DebugViewPP#70]
"(is een) test”

Wel lastig als je dan “een (optionele)? match” wilt doen. Daar moeten dan
nog een paar extra ()s omheen.

**Comment by janwilmans** [comment]
op zich leuk, maar welke usecase ondersteund dit?

**Comment by janwilmans** [comment]
usecase: highlighten van adressen of ids, waarbij de match is op bv "at address" in:

at address: 0x34556356

en waarbij je het getal wilt highlighten

ander voorbeeld: 

bla bla bla message (tid: 2433)

waarbij je 2433 wilt highlighten

**Comment by janwilmans** [comment]
implementatie is alleen eenvoudig als c++ group-syntax heeft voor reguliere expressies denk ik

**Comment by djeedjay** [comment]
Ik wil het niet als standaard gedrag van regex matches omdat het gebruik
van grouping in de regex dan een ongewenst zij-effect heeft. Ik bedenk
nu dat we een nieuw match type kunnen introduceren met dit gedrag:
RegexGroups. Daarmee is het een wijziging van +/- 10 regels code denk
ik ;-)

Me eens?

> implementatie is alleen eenvoudig als c++ group-syntax heeft voor
> reguliere expressies denk ik

**Comment by janwilmans** [comment]
Dat zou ik een erg mooie oplossing vinden, ik zeg doen!

Groeten,

Jan

2015-09-15 10:53 GMT+02:00 Gert-Jan de Vos <notifications@github.com>:

> Ik wil het niet als standaard gedrag van regex matches omdat het gebruik
> van grouping in de regex dan een ongewenst zij-effect heeft. Ik bedenk
> nu dat we een nieuw match type kunnen introduceren met dit gedrag:
> RegexGroups. Daarmee is het een wijziging van +/- 10 regels code denk
> ik ;-)
>
> Me eens?
>
> > implementatie is alleen eenvoudig als c++ group-syntax heeft voor
> > reguliere expressies denk ik
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djeedjay/DebugViewPP/issues/70#issuecomment-140326972>
> .
>



-- 
Met vriendelijke groeten,

Jan Wilmans

**Comment by djeedjay** [comment]
Done. Het waren 9 regels code extra :-)

Gert-Jan
