### ISSUE TITLE
Group messages by ThreadID using coloring

### ISSUE THREAD

**Issue by janwilmans** [djeedjay/DebugViewPP#8]
This could be done by logging the threadID in the message, for example:

	Foo::doFoo(1, 2, 3) enter (tid: 1234)
	dummy message (tid: 555)
	dummy message (tid: 555)
	Foo::doBar(1, 2) enter (tid: 1234)
	dummy message (tid: 666)
	dummy message (tid: 666)
	Foo::doBar(1, 2) leave -> 4 (tid: 1234)
	Foo::doBar(1, 2) leave (tid: 1234)

It would be useful to follow the code-flow if the lines from the same TID could have the same color _or_ where indented at the same level:

	    Foo::doFoo(1, 2, 3) enter (tid: 1234)
	dummy message (tid: 555)
	dummy message (tid: 555)
	    Foo::doBar(1, 2) enter (tid: 1234)
	dummy message (tid: 666)
	dummy message (tid: 666)
	    Foo::doBar(1, 2) leave -> 4 (tid: 1234)
	    Foo::doBar(1, 2) leave (tid: 1234)

**Comment by janwilmans** [comment]
@djeedjay kunnen deze ook in 9 regels toevoegen? nieuwe combinatie van regexgroups + een nieuw filertype 'color by token' de werking zou de zijn zoals process coloring, zodat wanneer twee dezelfde token gevonden worden deze regels dezelfde kleur krijgen

**Comment by djeedjay** [comment]
Ik weet wel een vrij eenvoudige implementatie maar het is niet heel intuitief wat het doet. De kleurstelling moet bijv. dynamisch zijn, We zouden zoals bij de exclude filter, de kleuren boxes kunnen disablen. Ik voorzie ook vrij snel een explosie van kleuren. Wordt case: “\.”, krijgt iedere character zijn eigen kleur :) Ik kan me voorstellen dat de redraw dan ook wat langzamer wordt…

Gert-Jan

**Comment by janwilmans** [comment]
Ik kom terug op mijn laatste email, het zou geen "regexgroups + een nieuw
filertype 'color by token' " moeten zijn, maar
alleen een nieuw filtertype 'Matching color', waarbij we de kleuren boxes
disablen.

De kleurstelling zou idd dynamisch zijn.

Het is inderdaad niet echt een intuïtief filter; wat ik eigenlijk met name
wil bereiken is regels van dezelfde thread dezelfde achtergrond kleur geven.
Misschien kunnen we daar een betere / intuïtieve oplossing voor bedenken?
Ik vind de process-colors wel intuïtief.

De gebruiker kan er een bende van maken, dat klopt, maar dat is nu ook al
zo, als je wat meer token-filters toevoegt.
Misschien moeten we de 'filter' automatisch op 'token' zetten als je
'regexgroups' selecteert, want de andere combinaties hebben eigenlijk geen
zinvolle betekenis.


Groeten,

Jan

2015-09-20 21:42 GMT+02:00 Gert-Jan de Vos <notifications@github.com>:

> Ik weet wel een vrij eenvoudige implementatie maar het is niet heel
> intuitief wat het doet. De kleurstelling moet bijv. dynamisch zijn, We
> zouden zoals bij de exclude filter, de kleuren boxes kunnen disablen. Ik
> voorzie ook vrij snel een explosie van kleuren. Wordt case: “\.”, krijgt
> iedere character zijn eigen kleur :) Ik kan me voorstellen dat de redraw
> dan ook wat langzamer wordt…
>
> Gert-Jan
>
> > On 20 Sep 2015, at 19:41, Jan Wilmans <notifications@github.com> wrote:
> >
> > @djeedjay <https://github.com/djeedjay> kunnen deze ook in 9 regels
> toevoegen? nieuwe combinatie van regexgroups + een nieuw filertype 'color
> by token' de werking zou de zijn zoals process coloring, zodat wanneer twee
> dezelfde token gevonden worden deze regels dezelfde kleur krijgen
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/djeedjay/DebugViewPP/issues/8#issuecomment-141814006>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djeedjay/DebugViewPP/issues/8#issuecomment-141826055>.
>



-- 
Met vriendelijke groeten,

Jan Wilmans

**Comment by djeedjay** [comment]
Ik zal eens nadenken hoe de ui zo'n filter toch intuïtief kan presenteren.
Ik ben het wel met je eens dat RegexGroups het filter type zou moeten
fixeren op token. Voor de andere filters werkt het nu als alternatief voor
Regex maar dat heeft natuurlijk geen toegevoegde waarde.

Gert-Jan

**Comment by djeedjay** [comment]
Ha,

Het MatchColor filter zit er in. Kijk maar eens of het doet wat je verwacht.

Gert-Jan

**Comment by janwilmans** [comment]
Ik heb er meer zitten spelen, ik vind het echt heel fijn werken! Super!

Ik zie nog twee onverwachte dingen:

1) ik had verwacht dat het per hele regel zou werken (achtergrond kleur)
zoals process-colors, dat leek me het makkelijkst, maar jij hebt het nog
mooier gemaakt :)

Ik stel voor dat als je:

RegEx + MatchColors = gedrag zoals process-colors
RegExGroups + MatchColors = huidige MatchColors gedrag

2)
Als ik een nieuw 'include' filter maak, en ik verander 'simple' naar
'RegExGroups', dan wordt het 'type veld' disabled, maar het type blijft
include!



[image: Inline images 2]

Groeten,

Jan

2015-09-26 23:58 GMT+02:00 Gert-Jan de Vos <notifications@github.com>:

> Ha,
>
> Het MatchColor filter zit er in. Kijk maar eens of het doet wat je
> verwacht.
>
> Gert-Jan
>
>
> > On 21 Sep 2015, at 10:19, gert-jan.de.vos@on.nl wrote:
> >
> > Ik zal eens nadenken hoe de ui zo'n filter toch intuïtief kan
> presenteren.
> > Ik ben het wel met je eens dat RegexGroups het filter type zou moeten
> > fixeren op token. Voor de andere filters werkt het nu als alternatief
> voor
> > Regex maar dat heeft natuurlijk geen toegevoegde waarde.
> >
> > Gert-Jan
> >
> >> Ik kom terug op mijn laatste email, het zou geen "regexgroups + een
> nieuw
> >> filertype 'color by token' " moeten zijn, maar
> >> alleen een nieuw filtertype 'Matching color', waarbij we de kleuren
> boxes
> >> disablen.
> >>
> >> De kleurstelling zou idd dynamisch zijn.
> >>
> >> Het is inderdaad niet echt een intuïtief filter; wat ik eigenlijk met
> name
> >> wil bereiken is regels van dezelfde thread dezelfde achtergrond kleur
> >> geven.
> >> Misschien kunnen we daar een betere / intuïtieve oplossing voor
> bedenken?
> >> Ik vind de process-colors wel intuïtief.
> >>
> >> De gebruiker kan er een bende van maken, dat klopt, maar dat is nu ook
> al
> >> zo, als je wat meer token-filters toevoegt.
> >> Misschien moeten we de 'filter' automatisch op 'token' zetten als je
> >> 'regexgroups' selecteert, want de andere combinaties hebben eigenlijk
> geen
> >> zinvolle betekenis.
> >>
> >>
> >> Groeten,
> >>
> >> Jan
> >>
> >> 2015-09-20 21:42 GMT+02:00 Gert-Jan de Vos <notifications@github.com>:
> >>
> >>> Ik weet wel een vrij eenvoudige implementatie maar het is niet heel
> >>> intuitief wat het doet. De kleurstelling moet bijv. dynamisch zijn, We
> >>> zouden zoals bij de exclude filter, de kleuren boxes kunnen disablen.
> Ik
> >>> voorzie ook vrij snel een explosie van kleuren. Wordt case: “\.”,
> krijgt
> >>> iedere character zijn eigen kleur :) Ik kan me voorstellen dat de
> redraw
> >>> dan ook wat langzamer wordt…
> >>>
> >>> Gert-Jan
> >>>
> >>>> On 20 Sep 2015, at 19:41, Jan Wilmans <notifications@github.com>
> >>> wrote:
> >>>>
> >>>> @djeedjay <https://github.com/djeedjay> kunnen deze ook in 9 regels
> >>> toevoegen? nieuwe combinatie van regexgroups + een nieuw filertype
> >>> 'color
> >>> by token' de werking zou de zijn zoals process coloring, zodat wanneer
> >>> twee
> >>> dezelfde token gevonden worden deze regels dezelfde kleur krijgen
> >>>>
> >>>> —
> >>>> Reply to this email directly or view it on GitHub <
> >>>
> https://github.com/djeedjay/DebugViewPP/issues/8#issuecomment-141814006>.
> >>>>
> >>>
> >>> —
> >>> Reply to this email directly or view it on GitHub
> >>> <
> https://github.com/djeedjay/DebugViewPP/issues/8#issuecomment-141826055>.
> >>>
> >>
> >>
> >>
> >> --
> >> Met vriendelijke groeten,
> >>
> >> Jan Wilmans
> >>
> >>
> >> ---
> >> Reply to this email directly or view it on GitHub:
> >> https://github.com/djeedjay/DebugViewPP/issues/8#issuecomment-141895480
> <https://github.com/djeedjay/DebugViewPP/issues/8#issuecomment-141895480>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djeedjay/DebugViewPP/issues/8#issuecomment-143499245>.
>



-- 
Met vriendelijke groeten,

Jan Wilmans

**Comment by janwilmans** [comment]
Example:
RegexGroups + Token  to highlight hex-addresses
Regex + MatchColor to highlight logging from the same thread!

![image](https://cloud.githubusercontent.com/assets/5933444/10122904/c12ea53c-6528-11e5-9417-56d80ec56970.png)

**Comment by djeedjay** [comment]
Ik heb al een tijdje zitten denken over wat RegexGroups + MatchColors zou moeten betekenen.

Ik vreesde dat ik dit zou moeten bouwen:

filter = “(#\d+) address ([0-9a-fA-F]+)”

En dan:

Example #1 address 00008FFF
Example #2 address 00009000
Example #1 address 00008FFF

Waarbij dus alleen de groepen zelf een kleur krijgen. Ik moet dan de groepen in m_matchColors opslaan, zoiets als:

	“#1\000008FFF” -> red
	“#2\000009000” -> green

Dat kan wel maar is toch gauw weer een avondje puzzelen. Ik wil nog wat ervaring opdoen met de huidige implementatie en even nadenken over jouw line highlight suggestie.

Ik had me niet zo druk gemaakt over de content van een disabled veld omdat het in min belevenis niets betekent. Als jij het fijn vindt dat RegexGroups ook Token selecteert kan dat wel.

ColorMatch werkt met Simple filters maar is dan eigenlijk alleen een truuk om een random kleur door de tool te laten kiezen. Moeten we die dan ook disabelen?

Gert-Jan

**Comment by djeedjay** [comment]
Leuk voorbeeld! Ik begin het tool onderhand wel een beetje over de top te vinden voor een een logging tool ;-) Ik blijf ook versteld staan van de hippe kleurtjes die de tool verzint, ik heb daar zelf helemaal geen talent voor..

G-J

**Comment by janwilmans** [comment]
Ik vind de kleuren geweldig, omdat je nu inzichtelijk kunt maken wat bij elkaar hoort. Je moet natuurlijk nog steeds de informatie zelf in de logging stoppen, maar toch.

Voor motion is dit heel handig wanneer bewegingen van verschillende controllers met elkaar interacteren.

**Comment by janwilmans** [comment]
Ik zit er over na te denken, het huidige gedrag van MatchColors is eigenlijk logischer bij:
Match: <dont care>, Type: Token, BG: <Auto>, FG: black

Het gedrag met hele regels zou je specificeren als:
Match <dont care>, Type: Highlight, BG: <Auto>, FG: black

Het Type '<MatchColors> zou dan verdwijnen, maar de ColorDialog zou uitgebreid worden met een extra optie 'Auto Matching color'

Ik vind die optie van  MatchColors+ RegExGroups wel een interessante gedachte, maar kan nog geen toepassing bedenken.

Wat betreft de content van een disabled veld, zou niets moeten betekenen, maar op die moment heeft het WEL invloed...

Ik vind het duidelijker er 'token' van de maken, in het geval van 'regexgroups'

**Comment by djeedjay** [comment]
Je bedoel dat er een Auto vinkje op de ColorDialog komt die dan het ColorMatch gedrag geeft. Dus:

Regex, Highlight, Auto Color -> color matching per line
Regex, Token, Auto Color -> color matching per token
RegexGroups, Token, Auto Color -> color matching per token group

Interessant, maar dan zit deze coole feature nogal subtiel verstopt. We aardig dat je zo zowel line
als token highlighting kunt maken. Ik ben benieuwd of andere gebruikers het ColorMatch filter
snappen en hoe zij daar over denken. Hoe populair is ons tooltje eigenlijk bij FEI?

O ja, die auto Token select zit er in. De Regex error feedback ook.

G-J

**Comment by djeedjay** [comment]
Ha,

Ik heb het nog eens uitgezocht: ik kan de ColorDialog vrij eenvoudig uitbreiden met een Auto checkboxje,
net als bij de FileOptionDialog. Maar je kunt dan niet eenvoudig laten zien dat de kleuren selectie niet van
toepassing is. De gekleurde vierkantjes lijken ge-custom paint te worden, ze staan niet in de resource
definitie van de ColorDialog.

We kunnen het dus zo doen en accepteren dat de Auto optie een nogal verstopte UI heeft.

Alternatieven zijn zelf een color selectie dialoog maken, een expliciete Match of FilterType optie zoals nu.
Of een extra kolom in het property grid, maar die is dan voor de meeste filters weer niet van toepassing.
Lastig hoor..

Groeten,

Gert-Jan

**Comment by janwilmans** [comment]
Ik vind het helemaal niet erg als de optie een beetje 'verstopt' zit, je
ziet het effect zodra je het color-dialoog afsluit; namelijk dat de bg/fg
color disabled raakt.

Groeten,

Jan

2015-09-28 20:09 GMT+02:00 Gert-Jan de Vos <notifications@github.com>:

> Ha,
>
> Ik heb het nog eens uitgezocht: ik kan de ColorDialog vrij eenvoudig
> uitbreiden met een Auto checkboxje,
> net als bij de FileOptionDialog. Maar je kunt dan niet eenvoudig laten
> zien dat de kleuren selectie niet van
> toepassing is. De gekleurde vierkantjes lijken ge-custom paint te worden,
> ze staan niet in de resource
> definitie van de ColorDialog.
>
> We kunnen het dus zo doen en accepteren dat de Auto optie een nogal
> verstopte UI heeft.
>
> Alternatieven zijn zelf een color selectie dialoog maken, een expliciete
> Match of FilterType optie zoals nu.
> Of een extra kolom in het property grid, maar die is dan voor de meeste
> filters weer niet van toepassing.
> Lastig hoor..
>
> Groeten,
>
> Gert-Jan
>
> > On 27 Sep 2015, at 20:11, Gert-Jan de Vos <gert-jan.de.vos@on.nl> wrote:
> >
> > Je bedoel dat er een Auto vinkje op de ColorDialog komt die dan het
> ColorMatch gedrag geeft. Dus:
> >
> > Regex, Highlight, Auto Color -> color matching per line
> > Regex, Token, Auto Color -> color matching per token
> > RegexGroups, Token, Auto Color -> color matching per token group
> >
> > Interessant, maar dan zit deze coole feature nogal subtiel verstopt. We
> aardig dat je zo zowel line
> > als token highlighting kunt maken. Ik ben benieuwd of andere gebruikers
> het ColorMatch filter
> > snappen en hoe zij daar over denken. Hoe populair is ons tooltje
> eigenlijk bij FEI?
> >
> > O ja, die auto Token select zit er in. De Regex error feedback ook.
> >
> > G-J
> >
> >
> >> On 27 Sep 2015, at 16:59, Jan Wilmans <notifications@github.com
> <mailto:notifications@github.com>> wrote:
> >>
> >> Ik zit er over na te denken, het huidige gedrag van MatchColors is
> eigenlijk logischer bij:
> >> Match: , Type: Token, BG: , FG: black
> >>
> >> Het gedrag met hele regels zou je specificeren als:
> >> Match , Type: Highlight, BG: , FG: black
> >>
> >> Het Type ' zou dan verdwijnen, maar de ColorDialog zou uitgebreid
> worden met een extra optie 'Auto Matching color'
> >>
> >> Ik vind die optie van MatchColors+ RegExGroups wel een interessante
> gedachte, maar kan nog geen toepassing bedenken.
> >>
> >> Wat betreft de content van een disabled veld, zou niets moeten
> betekenen, maar op die moment heeft het WEL invloed...
> >>
> >> Ik vind het duidelijker er 'token' van de maken, in het geval van
> 'regexgroups'
> >>
> >> —
> >> Reply to this email directly or view it on GitHub <
> https://github.com/djeedjay/DebugViewPP/issues/8#issuecomment-143564858>.
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djeedjay/DebugViewPP/issues/8#issuecomment-143830376>.
>



-- 
Met vriendelijke groeten,

Jan Wilmans

**Comment by janwilmans** [comment]
Hm, ik zit te denken misschien kunnen we zo doen:

[image: Inline images 3]

Eventueel zou je een keuze kunnen maken of je de achtergrond of de
voorgrond kleur 'automatic' maakt,
maar ik vind het eerlijk gezegd ook prima als dat alleen voor de
achtergrond kleur beschikbaar is.

Groeten,

Jan


2015-09-28 20:12 GMT+02:00 Jan Wilmans <janwilmans@gmail.com>:

> Ik vind het helemaal niet erg als de optie een beetje 'verstopt' zit, je
> ziet het effect zodra je het color-dialoog afsluit; namelijk dat de bg/fg
> color disabled raakt.
>
> Groeten,
>
> Jan
>
> 2015-09-28 20:09 GMT+02:00 Gert-Jan de Vos <notifications@github.com>:
>
>> Ha,
>>
>> Ik heb het nog eens uitgezocht: ik kan de ColorDialog vrij eenvoudig
>> uitbreiden met een Auto checkboxje,
>> net als bij de FileOptionDialog. Maar je kunt dan niet eenvoudig laten
>> zien dat de kleuren selectie niet van
>> toepassing is. De gekleurde vierkantjes lijken ge-custom paint te worden,
>> ze staan niet in de resource
>> definitie van de ColorDialog.
>>
>> We kunnen het dus zo doen en accepteren dat de Auto optie een nogal
>> verstopte UI heeft.
>>
>> Alternatieven zijn zelf een color selectie dialoog maken, een expliciete
>> Match of FilterType optie zoals nu.
>> Of een extra kolom in het property grid, maar die is dan voor de meeste
>> filters weer niet van toepassing.
>> Lastig hoor..
>>
>> Groeten,
>>
>> Gert-Jan
>>
>> > On 27 Sep 2015, at 20:11, Gert-Jan de Vos <gert-jan.de.vos@on.nl>
>> wrote:
>> >
>> > Je bedoel dat er een Auto vinkje op de ColorDialog komt die dan het
>> ColorMatch gedrag geeft. Dus:
>> >
>> > Regex, Highlight, Auto Color -> color matching per line
>> > Regex, Token, Auto Color -> color matching per token
>> > RegexGroups, Token, Auto Color -> color matching per token group
>> >
>> > Interessant, maar dan zit deze coole feature nogal subtiel verstopt. We
>> aardig dat je zo zowel line
>> > als token highlighting kunt maken. Ik ben benieuwd of andere gebruikers
>> het ColorMatch filter
>> > snappen en hoe zij daar over denken. Hoe populair is ons tooltje
>> eigenlijk bij FEI?
>> >
>> > O ja, die auto Token select zit er in. De Regex error feedback ook.
>> >
>> > G-J
>> >
>> >
>> >> On 27 Sep 2015, at 16:59, Jan Wilmans <notifications@github.com
>> <mailto:notifications@github.com>> wrote:
>> >>
>> >> Ik zit er over na te denken, het huidige gedrag van MatchColors is
>> eigenlijk logischer bij:
>> >> Match: , Type: Token, BG: , FG: black
>> >>
>> >> Het gedrag met hele regels zou je specificeren als:
>> >> Match , Type: Highlight, BG: , FG: black
>> >>
>> >> Het Type ' zou dan verdwijnen, maar de ColorDialog zou uitgebreid
>> worden met een extra optie 'Auto Matching color'
>> >>
>> >> Ik vind die optie van MatchColors+ RegExGroups wel een interessante
>> gedachte, maar kan nog geen toepassing bedenken.
>> >>
>> >> Wat betreft de content van een disabled veld, zou niets moeten
>> betekenen, maar op die moment heeft het WEL invloed...
>> >>
>> >> Ik vind het duidelijker er 'token' van de maken, in het geval van
>> 'regexgroups'
>> >>
>> >> —
>> >> Reply to this email directly or view it on GitHub <
>> https://github.com/djeedjay/DebugViewPP/issues/8#issuecomment-143564858>.
>> >>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/djeedjay/DebugViewPP/issues/8#issuecomment-143830376>
>> .
>>
>
>
>
> --
> Met vriendelijke groeten,
>
> Jan Wilmans
>



-- 
Met vriendelijke groeten,

Jan Wilmans

**Comment by djeedjay** [comment]
Plaatjes ontbreken…

G-J

**Comment by janwilmans** [comment]
Implemented, so closing
